sudo: required
dist: trusty
language: java
matrix:
    exclude:
    - jdk: oraclejdk9
      env: RUNTIME=ol RUNTIME_VERSION=18.0.0.3
    - jdk: oraclejdk9
      env: RUNTIME=wlp RUNTIME_VERSION=18.0.0.3
jdk:
    - openjdk7
    - oraclejdk8
    - oraclejdk9
env:
    - RUNTIME=ol RUNTIME_VERSION=18.0.0.4
    - RUNTIME=ol RUNTIME_VERSION=18.0.0.3
    - RUNTIME=wlp RUNTIME_VERSION=18.0.0.4
    - RUNTIME=wlp RUNTIME_VERSION=18.0.0.3
cache:
    directories:
        - $HOME/.m2
before_install:
    - echo "Deleting old .m2 artifacts..."
    - rm -rf $HOME/.m2/repository/net/wasdev
    - rm -rf $HOME/.m2/repository/io/openliberty
    - echo 'Installing ci.common lib...'
    - git clone https://github.com/wasdev/ci.common.git ./ci.common
    - cd ./ci.common
    - mvn clean install
    - cd ..
script:
  - travis_wait mvn verify -Ponline-its -Dinvoker.streamLogs=true -Druntime=$RUNTIME -DruntimeVersion=$RUNTIME_VERSION
