sudo: required
dist: trusty
language: java
jdk:
    - openjdk7
    - oraclejdk8
    - oraclejdk9
env:
    - RUNTIME=ol RUNTIME_VERSION=18.0.0.1
    - RUNTIME=ol RUNTIME_VERSION=18.0.0.2
    - RUNTIME=wlp RUNTIME_VERSION=18.0.0.1
    - RUNTIME=wlp RUNTIME_VERSION=18.0.0.2
cache:
    directories:
        - $HOME/.m2
before_install:
    - echo 'Installing ci.common lib ....'
    - git clone https://github.com/wasdev/ci.common.git ./ci.common
    - cd ./ci.common
    - mvn clean install
    - cd ..
script:
  - travis_wait mvn verify -Ponline-its -Dinvoker.streamLogs=true -Druntime=$RUNTIME -DruntimeVersion=$RUNTIME_VERSION
