environment:
  matrix:
        - jdk: "C:\\Program Files\\Java\\jdk1.8.0\\bin:"

install:
      - cmd: choco install maven
      - cmd: refreshenv
      - cmd: cd C:\ProgramData\chocolatey\lib\maven\apache-maven-3.5.2\bin\
      - cmd: COPY mvn.cmd mvn.bat
      - cmd: COPY mvnDebug.cmd mvnDebug.bat
      - cmd: cd C:\projects\ci-maven
      - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-http-proxy.ps1'))
      - ps: .\appveyor.ps1

build_script:
  # Build the compiled extension
  - "mvn verify -Ponline-its -Dinvoker.streamLogs=true -DwlpVersion=17.0.0.3"

test: off
