environment:
    matrix:
        - jdk: "C:\\Program Files\\Java\\jdk1.8.0\\bin:"
          RUNTIME_VERSION: 20.0.0.6
          RUNTIME: ol
        - jdk: "C:\\Program Files\\Java\\jdk1.8.0\\bin:"
          RUNTIME_VERSION: 20.0.0.3
          RUNTIME: ol
        - jdk: "C:\\Program Files\\Java\\jdk1.8.0\\bin:"
          RUNTIME_VERSION: 20.0.0.6
          RUNTIME: wlp
        - jdk: "C:\\Program Files\\Java\\jdk1.8.0\\bin:"
          RUNTIME_VERSION: 20.0.0.3
          RUNTIME: wlp

install:
    - cmd: |
        choco install maven
        refreshenv
        where mvn
        cd C:\projects\ci-maven
    - ps: .\appveyor.ps1

build_script:
    - "echo %WLP_VERSION%"
    - "mvn verify -Ponline-its -Dinvoker.streamLogs=true -Druntime=%RUNTIME% -DruntimeVersion=%RUNTIME_VERSION%"

test: off
